### ISSUE TITLE
Is it done?

### ISSUE THREAD

**Issue by DmitryTrish** [lopatinas/tinkoff-payment-bundle#1]
Привет. Не смог найти твоих контактов, поэтому спрошу тут
Этот бандл полностью в работоспособном состоянии? Я имею ввиду можно ли его юзать в продакшне?

**Comment by lopatinas** [comment]
Привет! Здесь реализованы не все методы обращения к API Тинькова, но для инициализации, подтверждения/отмены платежа использовать можно, на свой страх и риск, конечно же. :)
У меня используется на одном сайте.

**Comment by DmitryTrish** [comment]
Окей, спасибо большое :)
